apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aiinfra

resources:
  - namespace.yaml
  - configmap.yaml
  - mysql.yaml
  - redis.yaml
  - etcd.yaml
  - minio.yaml
  - milvus.yaml
  - gateway.yaml
  - inference.yaml
  - rag.yaml
  - agent.yaml
  - console.yaml
  - monitoring/prometheus.yaml
  - monitoring/grafana.yaml
  - monitoring/stack.yaml

configMapGenerator:
  - name: mysql-init
    files:
      - init.sql=../../scripts/init_db.sql
  - name: console-nginx
    files:
      - default.conf=console-nginx.conf

images:
  - name: aiinfra/gateway
    newName: aiinfra/gateway
    newTag: latest
  - name: aiinfra/rag
    newName: aiinfra/rag
    newTag: latest
  - name: aiinfra/inference
    newName: aiinfra/inference
    newTag: latest
  - name: aiinfra/agent
    newName: aiinfra/agent
    newTag: latest
  - name: aiinfra/console
    newName: aiinfra/console
    newTag: latest
